const allCards = [
  {
    id: "card_001",
    name: "Small Fry",
    value: 1,
    manaCost: 1,
    imageUrl: "/IMG_1.jpg",
    effect: null,
    description: "A very weak card, but it costs little mana.",
    attack: 1,
    defense: 1,
  },
  {
    id: "card_002",
    name: "Forest Spirit",
    value: 2,
    manaCost: 2,
    imageUrl: "/IMG_2.jpg",
    effect: null,
    description: "A basic creature of the woods.",
    attack: 2,
    defense: 2,
  },
  {
    id: "card_003",
    name: "Stone Golem",
    value: 3,
    manaCost: 3,
    imageUrl: "/IMG_3.jpg",
    effect: null,
    description: "Slow but sturdy.",
    attack: 2,
    defense: 4,
  },
  {
    id: "card_004",
    name: "Swift Scout",
    value: 4,
    manaCost: 4,
    imageUrl: "/IMG_4.jpg",
    effect: null,
    description: "Quick on its feet.",
    attack: 4,
    defense: 2,
  },
  {
    id: "card_005",
    name: "Mystic Owl",
    value: 5,
    manaCost: 5,
    imageUrl: "/IMG_5.jpg",
    effect: "Draw 1 card",
    description: "When played, draw 1 card from your deck.",
    attack: 3,
    defense: 3,
  },
  {
    id: "card_006",
    name: "Fire Elemental",
    value: 6,
    manaCost: 6,
    imageUrl: "/IMG_1.jpg", // Example: Reusing image
    effect: null,
    description: "Burns brightly.",
    attack: 6,
    defense: 4,
  },
  {
    id: "card_007",
    name: "Water Serpent",
    value: 7,
    manaCost: 7,
    imageUrl: "/IMG_2.jpg", // Example: Reusing image
    effect: null,
    description: "Flows with power.",
    attack: 5,
    defense: 7,
  },
  {
    id: "card_008",
    name: "Thunder Dragon",
    value: 8,
    manaCost: 8,
    imageUrl: "/IMG_3.jpg", // Example: Reusing image
    effect: null,
    description: "Strikes with lightning.",
    attack: 8,
    defense: 6,
  },
  {
    id: "card_009",
    name: "Ancient Guardian",
    value: 9,
    manaCost: 9,
    imageUrl: "/IMG_4.jpg", // Example: Reusing image
    effect: null,
    description: "Protector of ancient secrets.",
    attack: 7,
    defense: 9,
  },
  {
    id: "card_010",
    name: "Colossus",
    value: 10,
    manaCost: 10,
    imageUrl: "/IMG_5.jpg", // Example: Reusing image
    effect: null,
    description: "A powerful card, but requires a lot of mana.",
    attack: 10,
    defense: 10,
  },
];

module.exports = allCards;
