const allCards = [
  {
    id: "card_001",
    name: "ちびっこ",
    value: 1,
    manaCost: 1,
    imageUrl: "/IMG_1.jpg",
    effect: null,
    description: "とても弱いカードだが、マナコストは低い。",
    attack: 1,
    defense: 1,
  },
  {
    id: "card_002",
    name: "森の精霊",
    value: 2,
    manaCost: 2,
    imageUrl: "/IMG_2.jpg",
    effect: null,
    description: "森に住む基本的な生き物。",
    attack: 2,
    defense: 2,
  },
  {
    id: "card_003",
    name: "石のゴーレム",
    value: 3,
    manaCost: 3,
    imageUrl: "/IMG_3.jpg",
    effect: null,
    description: "動きは遅いが頑丈。",
    attack: 2,
    defense: 4,
  },
  {
    id: "card_004",
    name: "俊足の斥候",
    value: 4,
    manaCost: 4,
    imageUrl: "/IMG_4.jpg",
    effect: null,
    description: "素早い動きで敵を翻弄する。",
    attack: 4,
    defense: 2,
  },
  {
    id: "card_005",
    name: "神秘のフクロウ",
    value: 5,
    manaCost: 5,
    imageUrl: "/IMG_5.jpg",
    effect: "Draw 1 card",
    description: "プレイ時、デッキからカードを1枚引く。",
    attack: 3,
    defense: 3,
  },
  {
    id: "card_006",
    name: "炎のエレメンタル",
    value: 6,
    manaCost: 6,
    imageUrl: "/IMG_6.jpg",
    effect: null,
    description: "激しく燃え盛る。",
    attack: 6,
    defense: 4,
  },
  {
    id: "card_007",
    name: "水の蛇",
    value: 7,
    manaCost: 7,
    imageUrl: "/IMG_7.jpg",
    effect: null,
    description: "力強く流れる。",
    attack: 5,
    defense: 7,
  },
  {
    id: "card_008",
    name: "雷竜",
    value: 8,
    manaCost: 8,
    imageUrl: "/IMG_8.jpg",
    effect: null,
    description: "稲妻を伴って襲いかかる。",
    attack: 8,
    defense: 6,
  },
  {
    id: "card_009",
    name: "古の守護者",
    value: 9,
    manaCost: 9,
    imageUrl: "/IMG_9.jpg",
    effect: null,
    description: "古の秘密を守る者。",
    attack: 7,
    defense: 9,
  },
  {
    id: "card_010",
    name: "巨像",
    value: 10,
    manaCost: 10,
    imageUrl: "/IMG_10.jpg",
    effect: null,
    description: "強力なカードだが、多くのマナを必要とする。",
    attack: 10,
    defense: 10,
  },
];

module.exports = allCards;